### PR TITLE
CI: enable windows

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
CC @eseidelGoogle

**Comment by eseidelGoogle** [comment]
I'm a bit out of touch with the code to be a reviewer.  That said, it looks like all the bots failed, so probably not much to review yet?

**Comment by kevmoo** [comment]
@eseidelGoogle – this is almost entirely me just hacking around.

If you have windows working, submit another PR – please!

**Comment by kevmoo** [comment]
Failed attempt

**Pull request closed without merging**
