### PR TITLE
Independent wasmer bindings

### PR DESCRIPTION
**Pull request by modulovalue**
This PR depends on #109
The purpose of this PR is to streamline the wasmer bindings, this includes:

* merging wasmer_api.dart into runtime.dart (and adjusting the python macro)
* removing all unrelated import dependencies from the wasmer bindings through some minor DI.
* inlining the template files into the python macro to simplify things.

@liamappelbe I've decided to submit this PR to present to you why it would be beneficial for us to get rid of the singleton, as this wouldn't really be possible because we'd still have to somehow depend on wasm_locator (inside of runtime.dart) as long as we need a singleton.

### CODE REVIEW

**Comment by modulovalue** [comment]
@liamappelbe I do intend for this to land (it's not just an example, perhaps I was a little unclear about that).

**Comment by liamappelbe** [comment]
The DI changes are fine. Not sure why you want to merge all those files though.

The runtime/wasmer_api split is for readability. I find it easier to work with multiple small files than one big file, as long as the division is sensible. Here the split is that wasmer_api contains things that directly mirror (or thinly wrap) elements of the Wasmer C API, whereas runtime adds Dart specific logic (eg memory management) that makes the Wasmer C API more ergonomic.

I also like having the templates as standalone files, because it makes it easier to see where the generated files came from.

**Comment by liamappelbe** [comment]
If you add me as a reviewer, it's more likely I'll see the PR and do a proper code review.

**Comment by modulovalue** [comment]
> If you add me as a reviewer

I don't think github allows me to do that. Probably because I don't have the permissions to do that.

---

> Not sure why you want to merge all those files though.

In general, people tend to create files based on what they think should belong in a new file, which is highly subjective. I have a very objective rule for what should **not** belong in a new file: anything that can be [contracted](https://en.wikipedia.org/wiki/Edge_contraction) without affecting the underlying dependency graph.

Consider the dependency graphs that I posted in a previous PR. This PR brings us here: [link](https://edotor.net/?engine=dot#digraph%20%22%22%20%7B%0A%20%20graph%20%5Bstyle%3Drounded%20fontname%3D%22Arial%20Black%22%20fontsize%3D13%20penwidth%3D2.6%5D%3B%0A%20%20node%20%5Bshape%3Drect%20style%3D%22filled%2Crounded%22%20fontname%3DArial%20fontsize%3D15%20fillcolor%3DLavender%20penwidth%3D1.3%5D%3B%0A%20%20edge%20%5Bpenwidth%3D1.3%5D%3B%0A%20%20%22%2Fwasm.dart%22%20%5Blabel%3D%22wasm%22%5D%3B%0A%20%20%22%2Fsrc%2Fwasmer_locator.dart%22%20%5Blabel%3D%22wasmer_locator%22%5D%3B%0A%20%20%22%2Fsrc%2Fmodule.dart%22%20%5Blabel%3D%22module%22%5D%3B%0A%20%20%22%2Fsrc%2Fwasm_api.dart%22%20%5Blabel%3D%22wasm_api%22%5D%3B%0A%20%20%22%2Fsrc%2Fruntime.dart%22%20%5Blabel%3D%22runtime%22%5D%3B%0A%20%20%22%2Fsrc%2Fruntime.g.dart%22%20%5Blabel%3D%22runtime.g%22%5D%3B%0A%20%20%22%2Fsrc%2Ffactory%2Fengine_web.dart%22%20%5Blabel%3D%22engine_web%22%5D%3B%0A%20%20%22%2Fsrc%2Ffactory%2Fengine_io.dart%22%20%5Blabel%3D%22engine_io%22%5D%3B%0A%20%20%22%2Fsrc%2Ffactory%2Fengine.dart%22%20%5Blabel%3D%22engine%22%5D%3B%0A%20%20%22%2Fsrc%2Ffactory%2Fengine_unsupported.dart%22%20%5Blabel%3D%22engine_unsupported%22%5D%3B%0A%20%20subgraph%20%22cluster~%22%20%7B%0A%20%20%20%20label%3D%22lib%22%3B%0A%20%20%20%20%22%2Fwasm.dart%22%3B%0A%20%20%20%20subgraph%20%22cluster~%2Fsrc%22%20%7B%0A%20%20%20%20%20%20label%3D%22src%22%3B%0A%20%20%20%20%20%20%22%2Fsrc%2Fwasmer_locator.dart%22%3B%0A%20%20%20%20%20%20%22%2Fsrc%2Fmodule.dart%22%3B%0A%20%20%20%20%20%20%22%2Fsrc%2Fwasm_api.dart%22%3B%0A%20%20%20%20%20%20%22%2Fsrc%2Fruntime.dart%22%3B%0A%20%20%20%20%20%20%22%2Fsrc%2Fruntime.g.dart%22%3B%0A%20%20%20%20%20%20subgraph%20%22cluster~%2Fsrc%2Ffactory%22%20%7B%0A%20%20%20%20%20%20%20%20label%3D%22factory%22%3B%0A%20%20%20%20%20%20%20%20%22%2Fsrc%2Ffactory%2Fengine_web.dart%22%3B%0A%20%20%20%20%20%20%20%20%22%2Fsrc%2Ffactory%2Fengine_io.dart%22%3B%0A%20%20%20%20%20%20%20%20%22%2Fsrc%2Ffactory%2Fengine.dart%22%3B%0A%20%20%20%20%20%20%20%20%22%2Fsrc%2Ffactory%2Fengine_unsupported.dart%22%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%22%2Fwasm.dart%22%20-%3E%20%22%2Fsrc%2Ffactory%2Fengine.dart%22%20%5Bstyle%3Ddashed%5D%3B%0A%20%20%22%2Fwasm.dart%22%20-%3E%20%22%2Fsrc%2Fwasm_api.dart%22%20%5Bstyle%3Ddashed%5D%3B%0A%20%20%22%2Fsrc%2Fmodule.dart%22%20-%3E%20%22%2Fsrc%2Fruntime.dart%22%3B%0A%20%20%22%2Fsrc%2Fmodule.dart%22%20-%3E%20%22%2Fsrc%2Fwasm_api.dart%22%3B%0A%20%20%22%2Fsrc%2Fmodule.dart%22%20-%3E%20%22%2Fsrc%2Fwasmer_locator.dart%22%3B%0A%20%20%22%2Fsrc%2Ffactory%2Fengine_web.dart%22%20-%3E%20%22%2Fsrc%2Fwasm_api.dart%22%3B%0A%20%20%22%2Fsrc%2Ffactory%2Fengine_io.dart%22%20-%3E%20%22%2Fsrc%2Fmodule.dart%22%3B%0A%20%20%22%2Fsrc%2Ffactory%2Fengine_io.dart%22%20-%3E%20%22%2Fsrc%2Fwasm_api.dart%22%3B%0A%20%20%22%2Fsrc%2Ffactory%2Fengine_unsupported.dart%22%20-%3E%20%22%2Fsrc%2Fwasm_api.dart%22%3B%0A%7D%0A)
And this is where we are right now: [link](https://edotor.net/?engine=dot#digraph%20%22%22%20%7B%0A%20%20graph%20%5Bstyle%3Drounded%20fontname%3D%22Arial%20Black%22%20fontsize%3D13%20penwidth%3D2.6%5D%3B%0A%20%20node%20%5Bshape%3Drect%20style%3D%22filled%2Crounded%22%20fontname%3DArial%20fontsize%3D15%20fillcolor%3DLavender%20penwidth%3D1.3%5D%3B%0A%20%20edge%20%5Bpenwidth%3D1.3%5D%3B%0A%20%20%22%2Fwasm.dart%22%20%5Blabel%3D%22wasm%22%5D%3B%0A%20%20%22%2Fsrc%2Fwasmer_locator.dart%22%20%5Blabel%3D%22wasmer_locator%22%5D%3B%0A%20%20%22%2Fsrc%2Fwasmer_api.g.dart%22%20%5Blabel%3D%22wasmer_api.g%22%5D%3B%0A%20%20%22%2Fsrc%2Fmodule.dart%22%20%5Blabel%3D%22module%22%5D%3B%0A%20%20%22%2Fsrc%2Fwasmer_api.dart%22%20%5Blabel%3D%22wasmer_api%22%5D%3B%0A%20%20%22%2Fsrc%2Fwasm_api.dart%22%20%5Blabel%3D%22wasm_api%22%5D%3B%0A%20%20%22%2Fsrc%2Fruntime.dart%22%20%5Blabel%3D%22runtime%22%5D%3B%0A%20%20%22%2Fsrc%2Fruntime.g.dart%22%20%5Blabel%3D%22runtime.g%22%5D%3B%0A%20%20%22%2Fsrc%2Ffactory%2Fengine_web.dart%22%20%5Blabel%3D%22engine_web%22%5D%3B%0A%20%20%22%2Fsrc%2Ffactory%2Fengine_io.dart%22%20%5Blabel%3D%22engine_io%22%5D%3B%0A%20%20%22%2Fsrc%2Ffactory%2Fengine.dart%22%20%5Blabel%3D%22engine%22%5D%3B%0A%20%20%22%2Fsrc%2Ffactory%2Fengine_unsupported.dart%22%20%5Blabel%3D%22engine_unsupported%22%5D%3B%0A%20%20subgraph%20%22cluster~%22%20%7B%0A%20%20%20%20label%3D%22lib%22%3B%0A%20%20%20%20%22%2Fwasm.dart%22%3B%0A%20%20%20%20subgraph%20%22cluster~%2Fsrc%22%20%7B%0A%20%20%20%20%20%20label%3D%22src%22%3B%0A%20%20%20%20%20%20%22%2Fsrc%2Fwasmer_locator.dart%22%3B%0A%20%20%20%20%20%20%22%2Fsrc%2Fwasmer_api.g.dart%22%3B%0A%20%20%20%20%20%20%22%2Fsrc%2Fmodule.dart%22%3B%0A%20%20%20%20%20%20%22%2Fsrc%2Fwasmer_api.dart%22%3B%0A%20%20%20%20%20%20%22%2Fsrc%2Fwasm_api.dart%22%3B%0A%20%20%20%20%20%20%22%2Fsrc%2Fruntime.dart%22%3B%0A%20%20%20%20%20%20%22%2Fsrc%2Fruntime.g.dart%22%3B%0A%20%20%20%20%20%20subgraph%20%22cluster~%2Fsrc%2Ffactory%22%20%7B%0A%20%20%20%20%20%20%20%20label%3D%22factory%22%3B%0A%20%20%20%20%20%20%20%20%22%2Fsrc%2Ffactory%2Fengine_web.dart%22%3B%0A%20%20%20%20%20%20%20%20%22%2Fsrc%2Ffactory%2Fengine_io.dart%22%3B%0A%20%20%20%20%20%20%20%20%22%2Fsrc%2Ffactory%2Fengine.dart%22%3B%0A%20%20%20%20%20%20%20%20%22%2Fsrc%2Ffactory%2Fengine_unsupported.dart%22%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%22%2Fwasm.dart%22%20-%3E%20%22%2Fsrc%2Ffactory%2Fengine.dart%22%20%5Bstyle%3Ddashed%5D%3B%0A%20%20%22%2Fwasm.dart%22%20-%3E%20%22%2Fsrc%2Fwasm_api.dart%22%20%5Bstyle%3Ddashed%5D%3B%0A%20%20%22%2Fsrc%2Fmodule.dart%22%20-%3E%20%22%2Fsrc%2Fruntime.dart%22%3B%0A%20%20%22%2Fsrc%2Fmodule.dart%22%20-%3E%20%22%2Fsrc%2Fwasm_api.dart%22%3B%0A%20%20%22%2Fsrc%2Fmodule.dart%22%20-%3E%20%22%2Fsrc%2Fwasmer_api.dart%22%3B%0A%20%20%22%2Fsrc%2Fruntime.dart%22%20-%3E%20%22%2Fsrc%2Fwasm_api.dart%22%3B%0A%20%20%22%2Fsrc%2Fruntime.dart%22%20-%3E%20%22%2Fsrc%2Fwasmer_api.dart%22%3B%0A%20%20%22%2Fsrc%2Fruntime.dart%22%20-%3E%20%22%2Fsrc%2Fwasmer_locator.dart%22%3B%0A%20%20%22%2Fsrc%2Ffactory%2Fengine_web.dart%22%20-%3E%20%22%2Fsrc%2Fwasm_api.dart%22%3B%0A%20%20%22%2Fsrc%2Ffactory%2Fengine_io.dart%22%20-%3E%20%22%2Fsrc%2Fmodule.dart%22%3B%0A%20%20%22%2Fsrc%2Ffactory%2Fengine_io.dart%22%20-%3E%20%22%2Fsrc%2Fwasm_api.dart%22%3B%0A%20%20%22%2Fsrc%2Ffactory%2Fengine_unsupported.dart%22%20-%3E%20%22%2Fsrc%2Fwasm_api.dart%22%3B%0A%7D%0A)

Notice how currently module depends on wasmer_api. That dependency is transitive because module also depends on runtime which also depends on wasmer_api. That means that we can contract the edge between runtime<->wasmer_api without changing the underlying dependency graph. Files that can be contracted should in my opinion be contracted and in my experience, this does help immensely with maintainability as it makes navigating a codebase much easier because we can rely on certain invariants to hold.

> Here the split is that wasmer_api contains things that directly mirror (or thinly wrap) elements of the Wasmer C API,

But that's not the case today, because bindings are being generated not just into `wasmer_api` but also into `runtime`. To fully implement that idea we'd have to move all the pure Wasmer related bindings into its own file and make sure that we don't have `module` depend on the pure Wasmer bindings (i.e. don't have a transitive dependency there as we have today.). (I'm not against that, but since we don't plan to expose the pure wasmer C bindings, I don't see that as absolutely necessary)

The contraction argument applies to python as well.
Also, here are all the questions that I asked myself about the template files that get automatically answered by inlining them into the python file:
 * What are those template files?
 * Why do they have this file ending? Do I need to learn a new language?
 * Does somebody else depend on them?
 * Who do I break if I edit them (should I rather just not edit them...)?
 
I hope you can see how the answers to these questions are not obvious to new maintainers. We can answer them implicitly, and therefore reduce complexity, by inlining the templates into the python file.

**Pull request closed without merging**
