### PR TITLE
cleanup where the error types are defined

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Review by liamappelbe — APPROVED** [review]

**Comment by modulovalue** [comment]
@kevmoo why?

**Comment by kevmoo** [comment]
@modulovalue – it's a standard convention.

Ideally nothing within `src` imports from the root of `lib` – it makes it easier to understand what's meant to be implementation vs public API

**Comment by modulovalue** [comment]
@kevmoo Will all due respect, I'd like to ask you: are you trying to force me to read something between the lines or are you simply completely oblivious to the fact that changes like these are severely slowing down the engineering velocity of this particular repo? (I'm really not trying to offend, I just don't know how else to put it.) This change breaks my PR #100 and ignores all context around it #92.

Also, note: this package is experimental. Why not run a cleanup pass **just before** it becomes officially supported?

Would you like to be included in the review process alongside liam (_who I assumed would be the tech lead for this repo and would be in charge of such stylistic choices_), or is there anything else I can do to make the collaboration between us more productive in the future?

**Comment by kevmoo** [comment]
@modulovalue I'm so sorry. Zero between the lines. I'm all over `dart-lang` packages (and others) just doing cleanup. Your contributions are WONDERFUL. I did not intend to break your in-flight PRs. @liamappelbe is much deeper technically than I, but I likely have stronger opinions about repo/package structure/layout/conventions.

DM me on twitter - https://twitter.com/kevmoo – happy to discuss in chat or VC! Again, my apologies – and thank you SO MUCH for your work here!

**Pull request merged**
