### PR TITLE
Update to the latest lints, bump min SDKs

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
@liamappelbe – should be ready to review new

**Comment by liamappelbe** [comment]
Looks like this is failing flakily at head. I'll have to investigate.

**Comment by kevmoo** [comment]
okay...

**Review by liamappelbe — APPROVED** [review]
I'm working on fixing the flaky CI failures, but that shouldn't block this PR. I need to bump the minimum SDK version anyway, so that I can do #95, which might fix the problem.

**Comment by kevmoo** [comment]
I clearly broke the flutter example test – that should be investigated!

**Pull request merged**
