### PR TITLE
Switch to a singleton store

### PR DESCRIPTION
**Pull request by liamappelbe**
This is one of the feature requests from #38

This change should be transparent to users at this stage, but will enable future features like sharing memory or functions between modules.

### CODE REVIEW

**Review by kevmoo — CHANGES_REQUESTED** [review]
Would you expand on the change here? Why is it done?

Also, does this change the public API?

If so, we need to bump the pubspec version and add a changelog entry

**Comment by liamappelbe** [comment]
> Would you expand on the change here? Why is it done?
> 
> Also, does this change the public API?
> 
> If so, we need to bump the pubspec version and add a changelog entry

Expanded the description a bit. This change doesn't affect the API at all.

**Comment by kevmoo** [comment]
Is it worth a changelog entry? It changes behavior, right?

Should we bump to v0.2.0?

**Comment by liamappelbe** [comment]
It doesn't change user facing behavior. Users don't have access to the stores.

**Comment by kevmoo** [comment]
@liamappelbe – then why are folks asking for the change? 😄 

This change does SOMETHING. There are reasons folks want the change, right?

Can't we put that in the changelog?

**Comment by liamappelbe** [comment]
It doesn't do anything by itself, but it will enable me to make some user facing changes that will go in the changelog. If you prefer, I can hold off submitting this until I have some of those changes to go with it.

**Comment by kevmoo** [comment]
> It doesn't do anything by itself, but it will enable me to make some user facing changes that will go in the changelog. If you prefer, I can hold off submitting this until I have some of those changes to go with it.

Oh! Well...okay then. 😄

**Review by kevmoo — APPROVED** [review]

**Comment by kevmoo** [comment]
FYI: https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change

**Comment by liamappelbe** [comment]
> FYI: https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change

Ok, from reading that, I think it probably does make sense to add a -dev version to the changelog, and group this change with the features that depend on it into a new minor version. Still getting used to this workflow 🙃

**Comment by kevmoo** [comment]
You can still *land* this change – but at least with a version bump and a `-dev`

**Pull request merged**
