### PR TITLE
Support Windows in setup.dart

### PR DESCRIPTION
**Pull request by liamappelbe**
Fixes https://github.com/dart-lang/wasm/issues/9

### CODE REVIEW

**Review by kevmoo — COMMENTED** [review]
Do you want to enable windows CI before we land this?

**Comment by liamappelbe** [comment]
Maybe. Can we exclude fn_import_exception_test?

**Comment by kevmoo** [comment]
I'm away from my keyboard now. You can skip on a certain platform with the
test package. Just look at the docs for it. Otherwise feel free to land as
is now. And I can come back and look at enabling Windows tests. Whatever
you want to do.

**Comment by liamappelbe** [comment]
I tried windows CI but the setup script isn't working on github's windows. Need to investigate how their environment is different to mine. But I'll submit this as-is for now.

**Pull request merged**
